appsettings:
  healthcheck: "healthy"

database:
  #address: "mongodb://host.docker.internal:27017/"
  address: "mongodb://localhost:27017/"
  databasename: testdb
  replicaset: ""

categoryapi:
  #url: "http://localhost:5000"
  url: "http://category-api-svc"